name: gentoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gentoo:
    runs-on: ubuntu-latest

    container: madhacking/gentoo

    steps:
      - run:  emerge dev-libs/libelf

      - uses: actions/checkout@v5

      - run:  cc src/*.c -o elftool -Os -flto -Wl,-s -lelf

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
