name: build with brew on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-26, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - run:  brew update
      - run:  brew install libelf

      - uses: actions/checkout@main

      - run:  brew --prefix libelf
      - run:  ls $(brew --prefix libelf)

      - run:  cc src/*.c -o elftool -Os -flto -Wl,-s -lelf -I "$(brew --prefix libelf)/include" -L "$(brew --prefix libelf)/lib"

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool


  brew-sanitizer:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-26, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - run:  brew update
      - run:  brew install libelf llvm

      - uses: actions/checkout@main

      - run:  |
          "$(brew --prefix llvm)/bin/clang" src/*.c -o elftool -g -lelf "$(brew --prefix libelf)/include" "$(brew --prefix libelf)/lib"

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
