name: Manjaro Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container: manjarolinux/base

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm gcc libelf

      - uses: actions/checkout@main

      - run:  cc src/*.c -o elftool -Os -flto -Wl,-s -lelf

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
