name: Rocky Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '9']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run:  dnf -y update
      - run:  dnf -y install xz gcc libelf
      - run:  |
          command -v curl > /dev/null || dnf -y install curl
          # https://bugs.launchpad.net/tripleo/+bug/1953156

      - uses: actions/checkout@main

      - run:  cc src/*.c -o elftool -Os -flto -Wl,-s -lelf

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool
