name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vcpkg:

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Asia/Shanghai

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['26.04', '24.04', '22.04']

    container: ubuntu:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v5

      - run:  ./build.sh

      - run:  ./elftool

      - run:  ./elftool --help
      - run:  ./elftool --version

      - run:  ./elftool -h
      - run:  ./elftool -V

      - run:  ./elftool print-interpreter elftool
      - run:  ./elftool print-soname elftool
      - run:  ./elftool print-needed elftool
      - run:  ./elftool print-rpath  elftool

      - run: curl -LO https://github.com/leleliu008/ppkg-package-manually-build/releases/download/xxd-9.2.0750-linux-glibc-s390x.release.tar.xz/xxd-9.2.0750-linux-glibc-s390x.release.tar.xz

      - run: tar xf xxd-*.tar.xz --strip-components=1

      - run:  ./elftool print-interpreter bin/xxd
      - run:  ./elftool print-soname bin/xxd
      - run:  ./elftool print-needed bin/xxd
      - run:  ./elftool print-rpath  bin/xxd
